name: Build APK

  on:
    push:
      branches:
        - master

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: AlAyhamApp
          path: app/build/outputs/apk/debug/app-debug.apk
